module.exports = {
  apps: [
    {
      name: "gb-web",
      script: "node_modules/.bin/next",
      args: "start",
      instances: 2,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      max_memory_restart: "512M",
      error_file: "logs/gb-web-error.log",
      out_file: "logs/gb-web-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "gb-ai-worker",
      script: "dist/services/workers/ai.worker.js",
      instances: 2,
      exec_mode: "fork",
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
      },
      error_file: "logs/gb-ai-worker-error.log",
      out_file: "logs/gb-ai-worker-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      watch: false,
      autorestart: true,
      restart_delay: 5000,
    },
    {
      name: "gb-email-worker",
      script: "dist/services/workers/email.worker.js",
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
      },
      error_file: "logs/gb-email-worker-error.log",
      out_file: "logs/gb-email-worker-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      autorestart: true,
      restart_delay: 3000,
    },
    {
      name: "gb-doc-worker",
      script: "dist/services/workers/document.worker.js",
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
      },
      error_file: "logs/gb-doc-worker-error.log",
      out_file: "logs/gb-doc-worker-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      autorestart: true,
      restart_delay: 3000,
    },
    {
      name: "gb-scheduler",
      script: "dist/services/workers/scheduler.worker.js",
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
      },
      cron_restart: "0 */6 * * *",
      error_file: "logs/gb-scheduler-error.log",
      out_file: "logs/gb-scheduler-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      autorestart: true,
    },
    {
      name: "gb-notification-worker",
      script: "dist/services/workers/notification.worker.js",
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
      },
      error_file: "logs/gb-notification-worker-error.log",
      out_file: "logs/gb-notification-worker-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      autorestart: true,
      restart_delay: 3000,
    },
  ],
};
